#!/usr/bin/expect
# Update My-Jupyter-Notebooks
cd /home/dong/github/My-Jupyter-Notebooks
spawn /usr/bin/git pull
sleep 1
spawn /usr/bin/git add --all
sleep 1
spawn /usr/bin/git commit -m "by push shell script"
sleep 1
spawn /usr/bin/git push -u origin master
sleep 1
expect -re "Username for 'https://github.com':"
sleep 1
send "dymaxionkim\n"
#expect -re "Password for 'https://dymaxion.kim@gmail.com@github.com':"
#sleep 1
#send "비밀번호\n"
interact

